import { z } from "zod";
export declare const PlayerDecisionViewSchema: z.ZodObject<{
    id: z.ZodString;
    stateVersion: z.ZodNumber;
    mode: z.ZodEnum<{
        EXPLORATION: "EXPLORATION";
        ENCOUNTER: "ENCOUNTER";
        COMBAT: "COMBAT";
        DOWNTIME: "DOWNTIME";
        REACTION: "REACTION";
        ADVANCEMENT: "ADVANCEMENT";
        CLARIFICATION: "CLARIFICATION";
    }>;
    owner: z.ZodEnum<{
        BILL: "BILL";
        RAVEN: "RAVEN";
        DIRECTOR: "DIRECTOR";
        BOTH: "BOTH";
    }>;
    situation: z.ZodString;
    eligibleActorIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
    constraints: z.ZodOptional<z.ZodString>;
    requiredInput: z.ZodOptional<z.ZodString>;
    legalOptions: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const PlayerActorViewSchema: z.ZodObject<{
    id: z.ZodString;
    controller: z.ZodEnum<{
        BILL: "BILL";
        RAVEN: "RAVEN";
    }>;
    name: z.ZodString;
    level: z.ZodNumber;
    abilities: z.ZodObject<{
        strength: z.ZodNumber;
        dexterity: z.ZodNumber;
        constitution: z.ZodNumber;
        intelligence: z.ZodNumber;
        wisdom: z.ZodNumber;
        charisma: z.ZodNumber;
    }, z.core.$strict>;
    proficiencyBonus: z.ZodNumber;
    armorClass: z.ZodNumber;
    maxHp: z.ZodNumber;
    currentHp: z.ZodNumber;
    temporaryHp: z.ZodNumber;
    speed: z.ZodNumber;
    conditions: z.ZodArray<z.ZodString>;
    deathSaves: z.ZodObject<{
        successes: z.ZodNumber;
        failures: z.ZodNumber;
    }, z.core.$strict>;
    publicNotes: z.ZodArray<z.ZodString>;
    resources: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        current: z.ZodNumber;
        maximum: z.ZodNumber;
    }, z.core.$strict>>>;
    scopedNotes: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        text: z.ZodString;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const PlayerViewSchema: z.ZodObject<{
    campaignId: z.ZodString;
    stateVersion: z.ZodNumber;
    worldDate: z.ZodObject<{
        yearDr: z.ZodNumber;
        month: z.ZodString;
        day: z.ZodNumber;
    }, z.core.$strict>;
    location: z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        status: z.ZodString;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>;
    sceneId: z.ZodString;
    actors: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        controller: z.ZodEnum<{
            BILL: "BILL";
            RAVEN: "RAVEN";
        }>;
        name: z.ZodString;
        level: z.ZodNumber;
        abilities: z.ZodObject<{
            strength: z.ZodNumber;
            dexterity: z.ZodNumber;
            constitution: z.ZodNumber;
            intelligence: z.ZodNumber;
            wisdom: z.ZodNumber;
            charisma: z.ZodNumber;
        }, z.core.$strict>;
        proficiencyBonus: z.ZodNumber;
        armorClass: z.ZodNumber;
        maxHp: z.ZodNumber;
        currentHp: z.ZodNumber;
        temporaryHp: z.ZodNumber;
        speed: z.ZodNumber;
        conditions: z.ZodArray<z.ZodString>;
        deathSaves: z.ZodObject<{
            successes: z.ZodNumber;
            failures: z.ZodNumber;
        }, z.core.$strict>;
        publicNotes: z.ZodArray<z.ZodString>;
        resources: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            name: z.ZodString;
            current: z.ZodNumber;
            maximum: z.ZodNumber;
        }, z.core.$strict>>>;
        scopedNotes: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    inventory: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        ownerActorId: z.ZodNullable<z.ZodString>;
        containerId: z.ZodNullable<z.ZodString>;
        quantity: z.ZodNumber;
        equippedSlots: z.ZodArray<z.ZodString>;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    npcs: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        status: z.ZodString;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    factions: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        status: z.ZodString;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    facts: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        kind: z.ZodString;
        text: z.ZodString;
    }, z.core.$strict>>;
    events: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        kind: z.ZodString;
        text: z.ZodString;
    }, z.core.$strict>>;
    clocks: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        status: z.ZodString;
        current: z.ZodNumber;
        maximum: z.ZodNumber;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    openThreads: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        status: z.ZodString;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    combat: z.ZodNullable<z.ZodObject<{
        id: z.ZodString;
        round: z.ZodNumber;
        currentActorId: z.ZodNullable<z.ZodString>;
        initiativeOrder: z.ZodArray<z.ZodString>;
        facts: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            text: z.ZodString;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    currentDecision: z.ZodObject<{
        id: z.ZodString;
        stateVersion: z.ZodNumber;
        mode: z.ZodEnum<{
            EXPLORATION: "EXPLORATION";
            ENCOUNTER: "ENCOUNTER";
            COMBAT: "COMBAT";
            DOWNTIME: "DOWNTIME";
            REACTION: "REACTION";
            ADVANCEMENT: "ADVANCEMENT";
            CLARIFICATION: "CLARIFICATION";
        }>;
        owner: z.ZodEnum<{
            BILL: "BILL";
            RAVEN: "RAVEN";
            DIRECTOR: "DIRECTOR";
            BOTH: "BOTH";
        }>;
        situation: z.ZodString;
        eligibleActorIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
        constraints: z.ZodOptional<z.ZodString>;
        requiredInput: z.ZodOptional<z.ZodString>;
        legalOptions: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>;
    recoveryStatus: z.ZodLiteral<"NONE">;
}, z.core.$strict>;
export type PlayerDecisionView = z.infer<typeof PlayerDecisionViewSchema>;
export type PlayerActorView = z.infer<typeof PlayerActorViewSchema>;
export type PlayerView = z.infer<typeof PlayerViewSchema>;
//# sourceMappingURL=views.d.ts.map